### PR TITLE
Added news category wih sub menu

### PR DESCRIPTION
**Pull request by JubrilEdu**
screen shot 2016-10-04 at 11 01 28 pm

### CODE REVIEW

**Comment by JubrilEdu** [comment]
@oswalpalash I tried creating a news category for a start

**Comment by oswalpalash** [comment]
You need to resolve conflicts.

**Comment by JubrilEdu** [comment]
@oswalpalash fixed it

**Review by oswalpalash — APPROVED** [review]
Cool

**Comment by JubrilEdu** [comment]
Thanks @oswalpalash ,I'm really glad. Can I add more categories?

**Comment by oswalpalash** [comment]
@djubreel Sure. Make an issue for this.

**Pull request merged**
